version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/output.zip
