version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - sam build -s build
      - export BUCKET=buckleytech-lambda
      - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
  artifacts:
    type: zip
    files:
      - template.yml
      - outputtemplate.yml